import type { AuditLog } from "@/lib/types/audit";

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "aud-001",
    timestamp: "2026-05-22T14:30:00+07:00",
    user_name: "Budi Santoso",
    user_role: "Staff Gudang",
    action: "CREATE",
    entity_type: "GoodsReceipt",
    entity_id: "gr-001",
    entity_label: "GR-20260522-0001",
    description: "Membuat penerimaan barang baru dari PT Sumber Makmur",
    old_values: null,
    new_values: {
      gr_number: "GR-20260522-0001",
      supplier_name: "PT Sumber Makmur",
      status: "DRAFT",
      total_items: 3,
    },
  },
  {
    id: "aud-002",
    timestamp: "2026-05-22T14:45:00+07:00",
    user_name: "Budi Santoso",
    user_role: "Staff Gudang",
    action: "UPDATE",
    entity_type: "GoodsReceipt",
    entity_id: "gr-001",
    entity_label: "GR-20260522-0001",
    description: "Memfinalisasi penerimaan barang",
    old_values: { status: "DRAFT" },
    new_values: { status: "COMPLETED" },
  },
  {
    id: "aud-003",
    timestamp: "2026-05-22T15:10:00+07:00",
    user_name: "Siti Rahayu",
    user_role: "Supervisor Gudang",
    action: "CREATE",
    entity_type: "Product",
    entity_id: "prod-010",
    entity_label: "Semen Portland 50kg",
    description: "Menambahkan produk baru: Semen Portland 50kg",
    old_values: null,
    new_values: {
      name: "Semen Portland 50kg",
      sku: "SMN-PRT-50",
      unit: "Sak",
      min_stock: 20,
      price: 75000,
    },
  },
  {
    id: "aud-004",
    timestamp: "2026-05-22T16:00:00+07:00",
    user_name: "Andi Wijaya",
    user_role: "Staff Gudang",
    action: "CREATE",
    entity_type: "GoodsIssue",
    entity_id: "gi-001",
    entity_label: "GI-20260522-0001",
    description: "Membuat pengeluaran barang ke Divisi Marketing",
    old_values: null,
    new_values: {
      gi_number: "GI-20260522-0001",
      destination: "Divisi Marketing",
      status: "DRAFT",
      total_items: 2,
    },
  },
  {
    id: "aud-005",
    timestamp: "2026-05-22T16:20:00+07:00",
    user_name: "Andi Wijaya",
    user_role: "Staff Gudang",
    action: "UPDATE",
    entity_type: "GoodsIssue",
    entity_id: "gi-001",
    entity_label: "GI-20260522-0001",
    description: "Memfinalisasi pengeluaran barang",
    old_values: { status: "DRAFT" },
    new_values: { status: "COMPLETED" },
  },
  {
    id: "aud-006",
    timestamp: "2026-05-23T08:30:00+07:00",
    user_name: "Budi Santoso",
    user_role: "Staff Gudang",
    action: "CREATE",
    entity_type: "Adjustment",
    entity_id: "adj-001",
    entity_label: "ADJ-20260523-0001",
    description:
      "Mengajukan penyesuaian stok: Cat Tembok Putih 5L (-5 unit, rusak)",
    old_values: null,
    new_values: {
      adj_number: "ADJ-20260523-0001",
      product: "Cat Tembok Putih 5L",
      qty_change: -5,
      reason: "Barang rusak saat penyimpanan",
      status: "PENDING",
    },
  },
  {
    id: "aud-007",
    timestamp: "2026-05-23T09:15:00+07:00",
    user_name: "Siti Rahayu",
    user_role: "Supervisor Gudang",
    action: "APPROVE",
    entity_type: "Adjustment",
    entity_id: "adj-001",
    entity_label: "ADJ-20260523-0001",
    description: "Menyetujui penyesuaian stok ADJ-20260523-0001",
    old_values: { status: "PENDING" },
    new_values: { status: "APPROVED", approved_by: "Siti Rahayu" },
  },
  {
    id: "aud-008",
    timestamp: "2026-05-23T10:00:00+07:00",
    user_name: "Siti Rahayu",
    user_role: "Supervisor Gudang",
    action: "UPDATE",
    entity_type: "Product",
    entity_id: "prod-003",
    entity_label: "Pipa PVC 3/4 inch",
    description: "Mengubah minimum stok produk Pipa PVC 3/4 inch",
    old_values: { min_stock: 50, price: 25000 },
    new_values: { min_stock: 75, price: 27500 },
  },
  {
    id: "aud-009",
    timestamp: "2026-05-23T11:30:00+07:00",
    user_name: "Andi Wijaya",
    user_role: "Staff Gudang",
    action: "CREATE",
    entity_type: "Adjustment",
    entity_id: "adj-002",
    entity_label: "ADJ-20260523-0002",
    description:
      "Mengajukan penyesuaian stok: Baut M10 (+20 unit, selisih stock opname)",
    old_values: null,
    new_values: {
      adj_number: "ADJ-20260523-0002",
      product: "Baut M10",
      qty_change: 20,
      reason: "Selisih stock opname",
      status: "PENDING",
    },
  },
  {
    id: "aud-010",
    timestamp: "2026-05-23T13:00:00+07:00",
    user_name: "Siti Rahayu",
    user_role: "Supervisor Gudang",
    action: "REJECT",
    entity_type: "Adjustment",
    entity_id: "adj-002",
    entity_label: "ADJ-20260523-0002",
    description:
      "Menolak penyesuaian stok ADJ-20260523-0002 — bukti tidak lengkap",
    old_values: { status: "PENDING" },
    new_values: {
      status: "REJECTED",
      rejected_by: "Siti Rahayu",
      reject_reason: "Bukti stock opname tidak lengkap",
    },
  },
  {
    id: "aud-011",
    timestamp: "2026-05-23T14:15:00+07:00",
    user_name: "Dewi Lestari",
    user_role: "Admin",
    action: "DELETE",
    entity_type: "Product",
    entity_id: "prod-008",
    entity_label: "Kabel NYM 2x1.5mm (Discontinued)",
    description: "Menghapus produk yang sudah tidak dijual",
    old_values: {
      name: "Kabel NYM 2x1.5mm (Discontinued)",
      sku: "KBL-NYM-215",
      current_stock: 0,
      status: "ACTIVE",
    },
    new_values: { status: "DELETED", deleted_at: "2026-05-23T14:15:00+07:00" },
  },
  {
    id: "aud-012",
    timestamp: "2026-05-24T08:00:00+07:00",
    user_name: "Budi Santoso",
    user_role: "Staff Gudang",
    action: "CREATE",
    entity_type: "GoodsReceipt",
    entity_id: "gr-002",
    entity_label: "GR-20260524-0001",
    description: "Membuat penerimaan barang dari CV Jaya Abadi",
    old_values: null,
    new_values: {
      gr_number: "GR-20260524-0001",
      supplier_name: "CV Jaya Abadi",
      status: "DRAFT",
      total_items: 5,
    },
  },
];
