import type { GoodsIssue } from "@/lib/types/dispatching";

export const MOCK_GOODS_ISSUES: GoodsIssue[] = [
  {
    id: "gi-1",
    gi_number: "GI-20260522-0001",
    date: "2026-05-22",
    destination: "Divisi Marketing",
    status: "COMPLETED",
    created_by: "Admin",
    created_at: "2026-05-22T09:00:00",
    items: [
      {
        id: "gii-1",
        product_id: "1",
        product_name: "Beras Premium 5kg",
        sku: "BRG-001",
        qty: 20,
        unit_name: "PCS",
        notes: "Untuk event promosi",
      },
      {
        id: "gii-2",
        product_id: "7",
        product_name: "Kopi Bubuk 250g",
        sku: "BRG-007",
        qty: 50,
        unit_name: "PCS",
        notes: null,
      },
    ],
  },
  {
    id: "gi-2",
    gi_number: "GI-20260523-0001",
    date: "2026-05-23",
    destination: "Proyek Renovasi Kantor",
    status: "COMPLETED",
    created_by: "Staff",
    created_at: "2026-05-23T11:30:00",
    items: [
      {
        id: "gii-3",
        product_id: "5",
        product_name: "Sabun Cuci Piring",
        sku: "BRG-005",
        qty: 30,
        unit_name: "PCS",
        notes: null,
      },
      {
        id: "gii-4",
        product_id: "6",
        product_name: "Deterjen Bubuk 1kg",
        sku: "BRG-006",
        qty: 15,
        unit_name: "KG",
        notes: "Kebutuhan cleaning service",
      },
      {
        id: "gii-5",
        product_id: "9",
        product_name: "Susu UHT 1L",
        sku: "BRG-009",
        qty: 24,
        unit_name: "PCS",
        notes: null,
      },
    ],
  },
  {
    id: "gi-3",
    gi_number: "GI-20260524-0001",
    date: "2026-05-24",
    destination: "Retur Vendor - PT Sumber Makmur",
    status: "DRAFT",
    created_by: "Staff",
    created_at: "2026-05-24T08:45:00",
    items: [
      {
        id: "gii-6",
        product_id: "2",
        product_name: "Minyak Goreng 2L",
        sku: "BRG-002",
        qty: 10,
        unit_name: "PCS",
        notes: "Produk cacat kemasan",
      },
      {
        id: "gii-7",
        product_id: "3",
        product_name: "Gula Pasir 1kg",
        sku: "BRG-003",
        qty: 25,
        unit_name: "KG",
        notes: "Expired mendekati batas",
      },
    ],
  },
  {
    id: "gi-4",
    gi_number: "GI-20260525-0001",
    date: "2026-05-25",
    destination: "Cabang Surabaya",
    status: "DRAFT",
    created_by: "Admin",
    created_at: "2026-05-25T14:00:00",
    items: [
      {
        id: "gii-8",
        product_id: "4",
        product_name: "Tepung Terigu 1kg",
        sku: "BRG-004",
        qty: 100,
        unit_name: "KG",
        notes: null,
      },
      {
        id: "gii-9",
        product_id: "10",
        product_name: "Mie Instan Goreng",
        sku: "BRG-010",
        qty: 200,
        unit_name: "PCS",
        notes: "Stok transfer rutin",
      },
      {
        id: "gii-10",
        product_id: "1",
        product_name: "Beras Premium 5kg",
        sku: "BRG-001",
        qty: 50,
        unit_name: "PCS",
        notes: null,
      },
    ],
  },
];
